language: node_js

sudo: false

stages:
  - build

node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install: 
  - npm install
  - npm run vscode:prepublish

jobs:
  include:
    - stage: build
      script:
        - npm run compile
        - npm run tslint

after_success:
- bash <(curl -s https://codecov.io/bash)
