language: node_js

sudo: false
env:
 - CODE_TESTS_PATH=$TRAVIS_BUILD_DIR/out/test/integrationtest CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/src/test/integrationtest/testfiles

stages:
  - build

node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install: 
  - npm install
  - npm run vscode:prepublish

jobs:
  include:
    - stage: build
      script:
        - npm run compile
        - npm run tslint
    - stage: integration test
      script: 
        - npm run integrationtest

after_success:
- bash <(curl -s https://codecov.io/bash)
