language: node_js

sudo: false
env:
 - CODE_TESTS_PATH=$TRAVIS_BUILD_DIR/out/test CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/src/test/testfiles

stages:
  #- build
  #- test
  - deploy

node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

jobs:
  include:
    # - stage: build
    #   script:
    #     - npm run compile
    #     - npm run tslint
    # - stage: test
    #   script:
    #     - npm run test
    - stage: deploy
      before_deploy:
        - git tag "insider"
        - vsce package
        - export RELEASE_PKG_FILE=$(ls *.vsix)
      deploy:
        provider: releases
        file_glob: true
        file: "${RELEASE_PKG_FILE}"
        api_key: ${Travis_CD}
        skip_cleanup: true
        on:
          all_branches: true


after_success:
- bash <(curl -s https://codecov.io/bash)
