language: node_js

sudo: false
env:
 - CODE_TESTS_PATH=$TRAVIS_BUILD_DIR/out/test CODE_TESTS_WORKSPACE=$TRAVIS_BUILD_DIR/src/test/testfiles

stages:
  - build
  - test
  - name: deploy
    if: tag =~ /^v\d+\.\d+\.\d+$/ AND repo = HaaLeo/vscode-timing


node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install

jobs:
  include:
    - stage: build
      script:
        - npm run compile
        - npm run test-compile
    - stage: test
      script:
        - npm run tslint
        - npm run test
    - stage: deploy
      before_deploy:
        - vsce publish -p ${VSC_PUBLISH_TOKEN}
        - vsce package
        - export RELEASE_PKG_FILE=$(ls *.vsix)
      script: skip
      deploy:
        provider: releases
        file_glob: true
        file: "${RELEASE_PKG_FILE}"
        api_key: ${Travis_CD}
        skip_cleanup: true
        on:
          tags: true

after_success:
- bash <(curl -s https://codecov.io/bash)
